// File: control.v
// Generated by MyHDL 0.11
// Date: Sat Dec 11 20:31:43 2021


`timescale 1ns/10ps

module control (
    opcode,
    func3,
    func7,
    size_sel,
    operation_sel,
    enable_write,
    PC_genrator_sel,
    imm_sel,
    rs2_or_imm_or_4,
    PC_or_rs1,
    ALU_or_load_or_immShiftedBy12,
    Shift_amount,
    Enable_Reg,
    sign_selection
);


input [6:0] opcode;
input [2:0] func3;
input [6:0] func7;
output [1:0] size_sel;
reg [1:0] size_sel;
output [4:0] operation_sel;
reg [4:0] operation_sel;
output enable_write;
reg enable_write;
output [1:0] PC_genrator_sel;
reg [1:0] PC_genrator_sel;
output [2:0] imm_sel;
reg [2:0] imm_sel;
output [1:0] rs2_or_imm_or_4;
reg [1:0] rs2_or_imm_or_4;
output PC_or_rs1;
reg PC_or_rs1;
output [1:0] ALU_or_load_or_immShiftedBy12;
reg [1:0] ALU_or_load_or_immShiftedBy12;
output [1:0] Shift_amount;
reg [1:0] Shift_amount;
output Enable_Reg;
reg Enable_Reg;
output [1:0] sign_selection;
reg [1:0] sign_selection;




always @(opcode, func3, func7) begin: CONTROL_CONTROL_CIR
    size_sel = 0;
    operation_sel = 0;
    PC_or_rs1 = 0;
    rs2_or_imm_or_4 = 0;
    enable_write = 0;
    ALU_or_load_or_immShiftedBy12 = 0;
    PC_genrator_sel = 0;
    Enable_Reg = 0;
    imm_sel = 0;
    Shift_amount = 0;
    sign_selection = 0;
    case (opcode)
        'h33: begin
            PC_or_rs1 = 1;
            rs2_or_imm_or_4 = 0;
            enable_write = 0;
            ALU_or_load_or_immShiftedBy12 = 0;
            PC_genrator_sel = 3;
            Enable_Reg = 1;
            if (((func3 == 0) && (func7 == 0))) begin
                operation_sel = 0;
            end
            else if (((func3 == 0) && (func7 == 32))) begin
                operation_sel = 0;
            end
            else if (((func3 == 4) && (func7 == 0))) begin
                operation_sel = 5;
            end
            else if (((func3 == 6) && (func7 == 0))) begin
                operation_sel = 4;
            end
            else if (((func3 == 7) && (func7 == 0))) begin
                operation_sel = 3;
            end
            else if (((func3 == 1) && (func7 == 0))) begin
                operation_sel = 6;
            end
            else if (((func3 == 5) && (func7 == 0))) begin
                operation_sel = 7;
            end
            else if (((func3 == 5) && (func7 == 32))) begin
                operation_sel = 13;
            end
            else if (((func3 == 2) && (func7 == 0))) begin
                operation_sel = 10;
            end
            else if (((func3 == 3) && (func7 == 0))) begin
                operation_sel = 11;
            end
            else if (((func3 == 0) && (func7 == 1))) begin
                operation_sel = 1;
            end
            else if (((func3 == 4) && (func7 == 1))) begin
                operation_sel = 2;
            end
            else if (((func3 == 5) && (func7 == 1))) begin
                operation_sel = 15;
            end
            else if (((func3 == 6) && (func7 == 1))) begin
                operation_sel = 16;
            end
            else begin
                operation_sel = 17;
            end
        end
        'h13: begin
            PC_or_rs1 = 1;
            rs2_or_imm_or_4 = 1;
            enable_write = 0;
            ALU_or_load_or_immShiftedBy12 = 0;
            imm_sel = 0;
            Shift_amount = 2;
            Enable_Reg = 1;
            if ((func3 == 0)) begin
                operation_sel = 0;
                PC_genrator_sel = 3;
            end
            else if ((func3 == 4)) begin
                operation_sel = 5;
                PC_genrator_sel = 3;
            end
            else if ((func3 == 6)) begin
                operation_sel = 4;
                PC_genrator_sel = 3;
            end
            else if ((func3 == 7)) begin
                operation_sel = 3;
                PC_genrator_sel = 3;
            end
            else if (((func3 == 1) && (func7 == 0))) begin
                operation_sel = 6;
                PC_genrator_sel = 3;
            end
            else if (((func3 == 5) && (func7 == 0))) begin
                operation_sel = 7;
                PC_genrator_sel = 3;
            end
            else if (((func3 == 5) && (func7 == 32))) begin
                operation_sel = 13;
                PC_genrator_sel = 3;
            end
            else if ((func3 == 2)) begin
                operation_sel = 10;
                PC_genrator_sel = 3;
            end
            else begin
                operation_sel = 11;
                PC_genrator_sel = 3;
            end
        end
        'h3: begin
            operation_sel = 0;
            enable_write = 0;
            PC_genrator_sel = 3;
            PC_or_rs1 = 1;
            rs2_or_imm_or_4 = 1;
            ALU_or_load_or_immShiftedBy12 = 1;
            imm_sel = 0;
            Shift_amount = 2;
            Enable_Reg = 1;
            case (func3)
                'h0: begin
                    size_sel = 0;
                    sign_selection = 0;
                end
                'h1: begin
                    size_sel = 1;
                    sign_selection = 1;
                end
                'h2: begin
                    size_sel = 2;
                    sign_selection = 2;
                end
                'h4: begin
                    size_sel = 0;
                    sign_selection = 2;
                end
                default: begin
                    size_sel = 1;
                    sign_selection = 2;
                end
            endcase
        end
        'h23: begin
            operation_sel = 0;
            PC_genrator_sel = 3;
            enable_write = 1;
            PC_or_rs1 = 1;
            rs2_or_imm_or_4 = 1;
            imm_sel = 1;
            Enable_Reg = 0;
            Shift_amount = 2;
            case (func3)
                'h0: begin
                    size_sel = 0;
                end
                'h1: begin
                    size_sel = 1;
                end
                default: begin
                    size_sel = 2;
                end
            endcase
        end
        'h63: begin
            PC_or_rs1 = 1;
            rs2_or_imm_or_4 = 0;
            enable_write = 0;
            imm_sel = 2;
            Enable_Reg = 0;
            Shift_amount = 0;
            case (func3)
                'h0: begin
                    operation_sel = 8;
                    PC_genrator_sel = 0;
                end
                'h1: begin
                    operation_sel = 9;
                    PC_genrator_sel = 0;
                end
                'h4: begin
                    operation_sel = 10;
                    PC_genrator_sel = 0;
                end
                'h5: begin
                    operation_sel = 12;
                    PC_genrator_sel = 0;
                end
                'h6: begin
                    operation_sel = 11;
                    PC_genrator_sel = 0;
                end
                default: begin
                    PC_genrator_sel = 0;
                    operation_sel = 14;
                end
            endcase
        end
        'h6f: begin
            operation_sel = 0;
            PC_genrator_sel = 1;
            enable_write = 0;
            PC_or_rs1 = 0;
            rs2_or_imm_or_4 = 2;
            ALU_or_load_or_immShiftedBy12 = 0;
            imm_sel = 4;
            Shift_amount = 0;
            Enable_Reg = 1;
        end
        'h67: begin
            operation_sel = 0;
            PC_genrator_sel = 2;
            enable_write = 0;
            rs2_or_imm_or_4 = 2;
            ALU_or_load_or_immShiftedBy12 = 0;
            imm_sel = 0;
            Shift_amount = 2;
            Enable_Reg = 1;
        end
        'h37: begin
            PC_genrator_sel = 3;
            enable_write = 0;
            ALU_or_load_or_immShiftedBy12 = 2;
            imm_sel = 3;
            Shift_amount = 1;
            Enable_Reg = 1;
        end
        'h73: begin
            Enable_Reg = 0;
        end
        default: begin
            operation_sel = 0;
            enable_write = 0;
            Shift_amount = 1;
            imm_sel = 3;
            Enable_Reg = 1;
            ALU_or_load_or_immShiftedBy12 = 0;
            PC_or_rs1 = 0;
            rs2_or_imm_or_4 = 1;
            PC_genrator_sel = 3;
        end
    endcase
end

endmodule
