// File: mux2_1.v
// Generated by MyHDL 0.11
// Date: Sat Dec 11 21:01:22 2021


`timescale 1ns/10ps

module mux2_1 (
    sel,
    out,
    i0,
    i1
);


input sel;
output [31:0] out;
reg [31:0] out;
input [31:0] i0;
input [31:0] i1;




always @(i1, sel, i0) begin: MUX2_1_MUX
    if ((sel == 0)) begin
        out = i0;
    end
    else begin
        out = i1;
    end
end

endmodule
