// File: mux8_1.v
// Generated by MyHDL 0.11
// Date: Sat Dec 11 21:09:58 2021


`timescale 1ns/10ps

module mux8_1 (
    i0,
    i1,
    i2,
    i3,
    i4,
    out,
    sel
);


input [31:0] i0;
input [31:0] i1;
input [31:0] i2;
input [31:0] i3;
input [31:0] i4;
output [31:0] out;
reg [31:0] out;
input [2:0] sel;




always @(sel, i1, i2, i4, i3, i0) begin: MUX8_1_MUX
    case (sel)
        'h0: begin
            out = i0;
        end
        'h1: begin
            out = i1;
        end
        'h2: begin
            out = i2;
        end
        'h3: begin
            out = i3;
        end
        'h4: begin
            out = i4;
        end
        'h5: begin
            out = i4;
        end
        'h6: begin
            out = i4;
        end
        default: begin
            out = i4;
        end
    endcase
end

endmodule
