// File: shifter.v
// Generated by MyHDL 0.11
// Date: Sat Dec 11 22:07:04 2021


`timescale 1ns/10ps

module shifter (
    data_in,
    sel,
    data_out
);


input [31:0] data_in;
input [1:0] sel;
output [31:0] data_out;
reg [31:0] data_out;




always @(data_in, sel) begin: SHIFTER_SHIFT
    case (sel)
        'h0: begin
            data_out = ($signed(data_in) << 1);
        end
        'h1: begin
            data_out = ($signed(data_in) << 12);
        end
        default: begin
            data_out = $signed(data_in);
        end
    endcase
end

endmodule
