// File: sign_extender.v
// Generated by MyHDL 0.11
// Date: Sat Dec 11 22:12:54 2021


`timescale 1ns/10ps

module sign_extender (
    data_in,
    sel,
    data_out
);


input [31:0] data_in;
input [1:0] sel;
output [31:0] data_out;
reg [31:0] data_out;




always @(data_in, sel) begin: SIGN_EXTENDER_LOGIC
    case (sel)
        'h0: begin
            data_out = data_in[8-1:0][32-1:0];
        end
        'h1: begin
            data_out = $signed(data_in[16-1:0])[32-1:0];
        end
        'h2: begin
            data_out = data_in;
        end
        default: begin
            data_out = data_in;
        end
    endcase
end

endmodule
